### ISSUE TITLE
Can you add parsing function?

### ISSUE THREAD

**Issue by ghost** [PseudoKnight/CHPlaceholderAPI#1]
Um, Can you make a new function which is Parsing placeholders.
Sorry for my poor English.. 

Example:

parse_papi([player], %vault_eco_balance_commas%)

returns -> $100,000

Thanks!

**Comment by PseudoKnight** [comment]
I think you're looking for set_placeholders(player(), '%vault_eco_balance_commas%'). If not, please clarify.

**Comment by ghost** [comment]
Thanks it worked!  Have a nice day
